export const keyboardBtns = Object.freeze({
  clear: { className: "btn clear-btn double-w", value: "AC" },
  divide: { className: "btn operations-btn", value: "/" },
  multiply: { className: "btn operations-btn", value: "*" },
  seven: { className: "btn num-btn", value: "7" },
  eight: { className: "btn num-btn", value: "8" },
  nine: { className: "btn num-btn", value: "9" },
  subtract: { className: "btn operations-btn", value: "-" },
  four: { className: "btn num-btn", value: "4" },
  five: { className: "btn num-btn", value: "5" },
  six: { className: "btn num-btn", value: "6" },
  add: { className: "btn operations-btn", value: "+" },
  one: { className: "btn num-btn", value: "1" },
  two: { className: "btn num-btn", value: "2" },
  three: { className: "btn num-btn", value: "3" },
  equals: { className: "btn eq-btn double-h", value: "=" },
  zero: { className: "btn num-btn double-w", value: "0" },
  decimal: { className: "btn num-btn", value: "." },
});
